### ISSUE TITLE
Check out Zotero/Mendele/Citavi

### ISSUE THREAD

**Issue by Mithunjack** [Mithunjack/Thesis-NeRFs#3]
While writing and reading important paper and blogs these apps can help to manage everything at the end.

**Comment by lukashass** [comment]
@Mithunjack If you are planning on putting your thesis in git, check out https://github.com/JabRef/jabref. It's nice because it can directly edit a .bib file in your project dir :wink:

**Comment by Mithunjack** [comment]
@lukashass Thanks man! I will definitely check it out while working.
